### ISSUE TITLE
Consider parsing whole CSS file, instead of single rules

### ISSUE THREAD

**Issue by dimitrisnl** [DimitrisNL/css-maid#2]
This is will work:

```css
.selector {
  display: flex;
}
```
This will throw error:

```css
.selector{
  display: flex;
}
.selector2{
  display: block;
}
```
